name: Build
on: [push]
jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .


  build:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12 

      - name: Install dependencies
        run: |
          pip install Flask pytest requests python-dotenv
          pip install -r requirements.txt || true

      - name: Run tests
        run: pytest app_test.py


  deploy-to-impaas:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ImPaaS-Deploy
        uses: /impaas/impaas-deploy@v3
        with:
          app-name: spotifyapp
          deployment-token: ${{ secrets.TEAM_TOKEN }}
          method: PLATFORM
